stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/clean_data

  model_building:
    cmd: python src/model_building.py
    deps:
      - data/clean_data
      - src/model_building.py
    outs:
      - models

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - data/clean_data
      - models
      - src/model_evaluation.py
