version: 2.1

executors:
  docker-executor:
    docker:
      - image: python:3.12-slim
    working_directory: ~/repo
    environment:
      DVC_REMOTE: $DO_BUCKET_NAME
      AWS_ACCESS_KEY_ID: $DO_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $DO_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $DO_REGION

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get update -y
            apt-get install -y git curl unzip zip
            pip install --upgrade pip
            pip install awscli
            pip install "dvc[s3]==3.50.0"
            pip install -r requirements.txt

      - run:
          name: Configure AWS CLI (DigitalOcean Spaces)
          command: |
            aws configure set aws_access_key_id $DO_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $DO_SECRET_ACCESS_KEY
            aws configure set default.region $DO_REGION

      - run:
          name: Configure DVC Remote for DO Spaces
          command: |
            dvc remote add -d -f myremote $DO_BUCKET_NAME
            dvc remote modify myremote access_key_id $DO_ACCESS_KEY_ID
            dvc remote modify myremote secret_access_key $DO_SECRET_ACCESS_KEY
            dvc remote modify myremote endpointurl $DO_ENDPOINT
            dvc remote modify myremote region $DO_REGION

      - run:
          name: Pull DVC Data
          command: dvc pull

      - run:
          name: Dataset Tests
          command: pytest tests/test_dataset.py -v

      - run:
          name: Run DVC Pipeline
          command: dvc repro

      - run:
          name: Model Tests
          command: pytest tests/test_model.py -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
